version: '3'

services:
  database:
    container_name: monorepo_database
    image: postgres:latest
    networks:
      - postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      TZ: 'UTC'
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  pgdata:
    driver: local

networks:
  postgres:
    driver: bridge
